spring:
  application:
    name: authentication-service
  config:
    import:
      - configserver:${CONFIG_SERVER:http://localhost:8888}
      - env.properties

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.innovatech.authentication: DEBUG
    org.hibernate: ERROR

authorization:
  jwt:
    secret: ${authorization.jwt.secret}
    expiration:
      days: ${authorization.jwt.expiration.days}