spring:
  application:
    name: authentication-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.innovatech.authentication: DEBUG
    org.hibernate: ERROR

authorization:
  jwt:
    secret: WriteHereYourSecretStringForTokenSigningCredentials
    expiration:
      days: 7