server:
  port: 8090

spring:
  application:
    name: trips-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmrtripsdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: gerardo261202#$%
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect