server:
  port: 9090

spring:
  application:
    name: authentication-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL_MSVC_AUTH}
    username: ${DB_USERNAME_MSVC_AUTH}
    password: ${DB_PASSWORD_MSVC_AUTH}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.innovatech.authentication.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

authorization:
  jwt:
    secret: WriteHereYourSecretStringForTokenSigningCredentials
    expiration:
      days: 14

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka