server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: trips
          uri: lb://trips-service
          predicates:
            - Path=/api/v1/trips/**
          filters:
            - AuthenticationFilter
        - id: authentication
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/authentication/**
        - id: roles
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/roles/**
          filters:
            - AuthenticationFilter
        - id: users
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: promos
          uri: lb://promos-service
          predicates:
            - Path=/api/v1/promos/**
          filters:
            - AuthenticationFilter
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter
        - id: profiles
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/profiles/**
          filters:
            - AuthenticationFilter

authorization:
  jwt:
    secret: WriteHereYourSecretStringForTokenSigningCredentials
    expiration:
      days: 14

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true