server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: trips
          uri:
            http://localhost:8090
          predicates:
            - Path=/api/v1/trips/**
          filters:
            - AuthenticationFilter
        - id: authentication
          uri:
            http://localhost:9090
          predicates:
            - Path=/api/v1/authentication/**
        - id: roles
          uri:
            http://localhost:9090
          predicates:
            - Path=/api/v1/roles/**
          filters:
            - AuthenticationFilter
        - id: users
          uri:
            http://localhost:9090
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: promos
          uri:
            http://localhost:8100
          predicates:
            - Path=/api/v1/promos/**
          filters:
            - AuthenticationFilter
        - id: notification
          uri:
            http://localhost:8105
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter
        - id: profiles
          uri:
            http://localhost:8095
          predicates:
            - Path=/api/v1/profiles/**
          filters:
            - AuthenticationFilter

authorization:
  jwt:
    secret: WriteHereYourSecretStringForTokenSigningCredentials
    expiration:
      days: 7

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true