eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: trips
          uri:
            http://localhost:8090
          predicates:
            - Path=/api/v1/trips/**
          filters:
            - AuthenticationFilter
        - id: authentication
          uri:
            http://localhost:9090
          predicates:
            - Path=/api/v1/authentication/**
        - id: promos
          uri:
            http://localhost:8100
          predicates:
            - Path=/api/v1/promos/**
          filters:
            - AuthenticationFilter
        - id: notification
          uri:
            http://localhost:8080
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - AuthenticationFilter