spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

authorization:
  jwt:
    secret: ${authorization.jwt.secret}
    expiration:
      days: ${authorization.jwt.expiration.days}